flags:
  ln-yesod:
    library-only: false
    dev: false
packages:
- '.'
- '../ln-lib'
- '../ln-sanitize'
- '../ln-validate'
- '../haskell-ln-types'
- '../haskell-api-helpers'
- '../haskell-ebyam'
- '../haskell-rehtie'
- '../haskell-ifte'
- '../yesod-auth-oauth2'
extra-deps: [stm-lifted-0.1.0.0, yesod-bootstrap-0.2.1, yesod-markdown-0.11.0, random-extras-0.19, text-regex-replace-0.1.1.1]
resolver: lts-6.4
